### ISSUE TITLE
Enable netlify to preview the changes done by developers in the PR

### ISSUE THREAD

**Issue by RaiVaibhav** [pythonindia/inpycon2019#21]
Hello everyone

This is not an issue rather a feature request which will help every developer in preview the changes made in the repo and give the review on the basis of the preview.

**Comment by astronomersiva** [comment]
This is already being done.

**Comment by RaiVaibhav** [comment]
Oh okay, didn't saw on the closed issue :+1:

**Comment by astronomersiva** [comment]
You can probably update the README's contributing section to make this more explicit. Maybe attach a screenshot from one of the closed PRs to point out where to access this?

**Comment by RaiVaibhav** [comment]
Yeah will update the Readme :+1:
