### ISSUE TITLE
Improve the navbar

### ISSUE THREAD

**Issue by astronomersiva** [pythonindia/inpycon2019#38]
<img width="1439" alt="Screen Shot 2019-05-01 at 12 27 22" src="https://user-images.githubusercontent.com/7725225/57008275-8a776a80-6c0c-11e9-995a-bb6c9782122a.png">

- Vertical center the text.
- Proper spacing around the logo
- Vertical align and style the toggle

<img width="591" alt="Screen Shot 2019-05-01 at 12 28 54" src="https://user-images.githubusercontent.com/7725225/57008297-bbf03600-6c0c-11e9-92a3-e73eb0c2d228.png">

**Comment by Sayak9495** [comment]
Hi @astronomersiva , Please review the screenshots. I have manually fixed using margin-top property.

![navbar-full](https://user-images.githubusercontent.com/16087116/57879082-3dfd7300-7839-11e9-97d4-dc45155a974f.png)
 
and navbar-collapsed

![navbar-toggle](https://user-images.githubusercontent.com/16087116/57879146-5ff6f580-7839-11e9-812a-6ad59d1208cc.png)

**Comment by astronomersiva** [comment]
Can you push this @Sayak9495? I would prefer checking out the preview.

**Comment by Sayak9495** [comment]
#75 Hi @astronomersiva ! Please review and let know if any changes are required.
