### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by astronomersiva** [pythonindia/inpycon2019#39]
<img width="1440" alt="Screen Shot 2019-05-01 at 12 29 36" src="https://user-images.githubusercontent.com/7725225/57008312-d0343300-6c0c-11e9-944c-5cd9e795a8ca.png">

All contents should be aligned and be on the same line

**Comment by Sayak9495** [comment]
Will align them on a single line which will be vertically centred. The padding/gaps between the footer elements are okay, I guess?

**Comment by astronomersiva** [comment]
Yes, it's sufficient if they are all on the same line.

**Comment by Sayak9495** [comment]
Hi @astronomersiva . Was wondering if the PR requires any updates?

**Comment by astronomersiva** [comment]
Let me take a look :)
