### ISSUE TITLE
Twitter feed interrupts scrolling

### ISSUE THREAD

**Issue by rohitsanj** [pythonindia/inpycon2019#53]
#### Here's a little GIF
![demo-inpycon](https://user-images.githubusercontent.com/39169550/57183587-d1938300-6ecc-11e9-8650-14c6d0c307b4.gif)

**Comment by astronomersiva** [comment]
We have made the Twitter feed smaller. This should not longer be an issue.

Thanks for spotting this though! Keep them coming :)
