### ISSUE TITLE
Dropdown broken in mobile view

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019#59]
The dropdown menu seems to be broken in mobile view. When the navbar becomes vertical, the dropdown becomes inaccessible.

![dropdown](https://user-images.githubusercontent.com/1171852/57240761-f7479600-704c-11e9-932a-a99207f4a4b5.png)

**Comment by sakthips** [comment]
Need to write media query for medium and smaller screen. 

This is the existing,
```
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
}
```

For Medium and Small screen, use this css
```
@media screen and (max-width: 768px) {
      .dropdown-content {
            display: none;
            max-width: 180px;
            margin: auto;
            background-color: #f1f1f1;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 1;
    }
}
```
just removed the Position absolute and add this two lines.
