### ISSUE TITLE
Keynote Speakers in Mobile View

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019#60]
![keynote](https://user-images.githubusercontent.com/1171852/57496423-87f1d080-72f0-11e9-87f4-478b51d5b4cf.png)

The keynote speakers section in mobile view has a few problems. The photo is smaller, and the colored border around it is too thick. And there is too much of white margin around the photo boxes.

**Comment by sakthips** [comment]
This is issue is because of, added width after the Grid separation. Just remove the width css from the 
below code.

@media screen and (max-width: 768px)
.orange, .blue {
    width: 60%; 
    margin: 30px auto
}

Just remove the Width from this media query. It will work for all the screen resolution
