### ISSUE TITLE
Implement a "Skip to Main Content" Feature on all pages

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019#69]
The intention is for people using software like screen readers to skip all navigational and header items at the top and reach the machine content of the page without having to tab through all the links and search box at the top.

https://www.w3.org/TR/WCAG20-TECHS/G1

**Comment by Sayak9495** [comment]
@sharmi . In [style.css](https://github.com/pythonindia/inpycon2019/blob/e418338a6510bb5b40a82d8ef77d5d017edfac43/assets/css/styles.css#L31), outline property is set to none. And thus it is little difficult to keep track of the links I'm currently on. I'm sure there must be a reason, and I'm just curious to know the reason. And please review the PR and let me if any changes are required.

**Comment by astronomersiva** [comment]
@Sayak9495, I have changed the outline property in a PR of mine. Looks like it was set to none for the sake of visual design.

**Comment by Sayak9495** [comment]
@astronomersiva oh! great.
