### ISSUE TITLE
Renew SSL certificate

### ISSUE THREAD

**Issue by astronomersiva** [pythonindia/inpycon2019#85]
The current SSL certificate expires on June 2. We need to check if there are auto-renewers set up...else we will have to renew them manually.

**Comment by astronomersiva** [comment]
@zerothabhishek @bravegnu

**Comment by bravegnu** [comment]
This seems suspicious. Shouldn't auto-renewal happen much earlier for Let's encrypt certificates?

**Comment by astronomersiva** [comment]
That really depends on how(and if) it has been set up. Netlify for example, will renew ten days before the expiry date. The certificate.did expire three months back and I remember mailing the people maintaining the server so I believe it has not been set up.

**Comment by vigneshsarma** [comment]
Right now the certificate is populated through a separate system and is manual. Have created this issue https://github.com/pythonindia/magudi/issues/26 to remove this manual intervention. For now, have manually updated the cert.

**Comment by bravegnu** [comment]
Can be considered done, for now.
