### ISSUE TITLE
Add contact email

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019#93]
Add contact email information contact@in.pycon.org to the bottom of the page.

**Comment by Sayak9495** [comment]
Should I add all the link i.e twitter,fb and mail-id. Like this -

![image](https://user-images.githubusercontent.com/16087116/58651723-a5361f80-832f-11e9-8011-5e8812145109.png)

p.s I think the twitter and fb handle would be same.

**Comment by Sayak9495** [comment]
@bravegnu Is there any favicon available with same theme? or should I add just the email-id without favicon?

**Comment by bravegnu** [comment]
@Sayak9495 What we have in the assets/images is all that we have got. I think we should add the email ID now, and get the image done later.
